version: '3'
services:
  ansible:
    container_name: ansible_test
    hostname: ansible_test
    image: philm/ansible_target
    ports:
      - "8080:80"
      - "2222:22"
    volumes:
      - ~/.ssh/id_rsa.pub:/home/ubuntu/.ssh/authorized_keys