- hosts: devoops
  remote_user: ubuntu
  tasks:
    - name: Install the package "nginx"
      apt:
        name: nginx
      become: yes
    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
      become: yes