- hosts: devoops
  remote_user: ubuntu
  become: yes
  tasks:
    #Locale Fixes for Mongodb
    - name: Set Locale
      command: locale-gen en_US.UTF-8
    - name: Update Locale
      command: update-locale
    # Install Packages
    - name: Install the packages
      apt:
        name: ["python-pip", "python-dev", "nginx", "gunicorn", "locales", "mongodb"]
        state: present
      # Nginx Configuration
    - name: Copy NGINX
      copy:
        src: ./nginx/conf/default
        dest: /etc/nginx/sites-available/
    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
    # Install Flask
    - name: Pip install Flask
      pip:
        name: flask
        state: present
      #Start Gunicorn
    - name: Spinup Gunicorn
      command: gunicorn --daemon --bind 0.0.0.0:5000 wsgi:app
      args:
        chdir: '/var/www/html'
        #Start Mongodb
    - name: Start Mongo
      command: mongod --fork --logpath=/var/log/mongodb/mongo.log --logappend